name: remote_preferences
description: A package to save preferences in the cloud.
version: 1.0.0
homepage:
maintainer: Breno Augusto

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.remote_preferences
        pluginClass: RemotePreferencesPlugin
      ios:
        pluginClass: RemotePreferencesPlugin